version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=WeatherApp
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:db_example
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.H2Dialect
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=debug
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL=trace
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=debug
      - SPRING_TRANSACTION_DEFAULT-TIMEOUT=30
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"  # Map port 4000 on the host to 4000 in the container for Vite
    volumes:
      - ./frontend:/app  # Mount the local frontend directory to the container
      - /app/node_modules  # Ensure node_modules in the container are not overwritten
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
