version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=WeatherApp
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:db_example
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=debug
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL=trace
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=debug
      - SPRING_TRANSACTION_DEFAULT_TIMEOUT=30
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_H2_CONSOLE_SETTINGS_WEBALLOWOTHERS=true
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
